In [1]:
!pip install --quiet mxnet

In [14]:
import mxnet as mx
from mxnet import nd
mx.random.seed(1)

/opt/conda/lib/python3.5/site-packages/jupyter_client/jsonutil.py:67: DeprecationWarning: Interpreting naive datetime as local 2017-08-30 15:30:15. Please add timezone info to timestamps.
  new_obj[k] = extract_dates(v)


In [24]:
x = nd.zeros((3, 5))
x


[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
<NDArray 3x5 @cpu(0)>

/opt/conda/lib/python3.5/site-packages/jupyter_client/jsonutil.py:67: DeprecationWarning: Interpreting naive datetime as local 2017-08-30 15:30:39. Please add timezone info to timestamps.
  new_obj[k] = extract_dates(v)


(3, 5)

/opt/conda/lib/python3.5/site-packages/jupyter_client/jsonutil.py:67: DeprecationWarning: Interpreting naive datetime as local 2017-08-30 15:31:20. Please add timezone info to timestamps.
  new_obj[k] = extract_dates(v)
